version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80

  db:
    image: redis:7.4.1
    ports:
      - 6379:6379
